import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";

import gsap from "gsap";
import { SplitText } from "gsap/SplitText";
import Lenis from "lenis";
import localFont from "next/font/local";
import { notFound } from "next/navigation";
import { ViewTransitions } from "next-view-transitions";
import LenisScrollProvider from "@/components/LenisProvider";
import Cursor from "@/components/shared/Cursor";
import Footer from "@/components/shared/Footer";
import Header from "@/components/shared/Header";

// Font files can be colocated inside of `app`
const Switzer = localFont({
	src: "../../public/fonts/Switzer-Variable.ttf",
	display: "swap",
	variable: "--font-switzer",
});

const PlayfairDisplay = Playfair_Display({
	subsets: ["latin"],
	variable: "--font-playfair-display",
});

export const metadata: Metadata = {
	title: "Kaloyanes",
	description: "Generated by create next app",
	keywords: ["Kaloyanes", "Kaloyanes.com", "Kaloyanes.com", "Kaloyanes.com"],
	authors: [{ name: "Kaloyanes", url: "https://kaloyanes.com" }],
	creator: "Kaloyanes",
	publisher: "Kaloyanes",
	openGraph: {
		title: "Kaloyanes",
		description: "Generated by create next app",
		images: ["/og-image.png"],
		siteName: "Kaloyanes",
		locale: "en_US",
		type: "website",
	},
	twitter: {
		card: "summary_large_image",
		site: "@kaloyanes",
		creator: "@kaloyanes",
	},
};

gsap.registerPlugin(SplitText);

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ViewTransitions>
			<html lang="en">
				<body
					className={`${Switzer.className} ${Switzer.variable} ${PlayfairDisplay.variable} antialiased *:cursor-none m-0 p-0 `}
				>
					<LenisScrollProvider>
						<div className="relative">
							<Cursor />
							<Header />

							{children}

							<Footer />
						</div>
					</LenisScrollProvider>
				</body>
			</html>
		</ViewTransitions>
	);
}
